# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sWkSI0JyAbKhJiMXxqO8nQF9QH45Q97
"""

import sys
!{sys.executable} -m pip install PyMuPDF pyttsx3 streamlit nltk gTTS
!apt-get update && apt-get install espeak

import streamlit as st
import pyttsx3
import os
import fitz  # PyMuPDF
import nltk
import re
from gtts import gTTS
from IPython.display import Audio, display
from nltk.tokenize import sent_tokenize

# Download NLTK data
nltk.download('punkt')
nltk.download('punkt_tab') # Download the missing 'punkt_tab' resource

# Save this as app.py
# -------------------------------
# Install dependencies:
# pip install streamlit PyMuPDF nltk gTTS
# -------------------------------

# Download NLTK data
nltk.download('punkt')

st.set_page_config(page_title="PDF to Speech", page_icon="🎧")
st.title("📄 PDF to Human-Like Speech Reader")
st.markdown("Upload a PDF and listen to it in a natural human-like voice!")

# -------------------------------
# 1️⃣ Upload PDF
# -------------------------------
pdf_file = st.file_uploader("Upload a PDF file", type=["pdf"])

# -------------------------------
# 2️⃣ Helper Functions
# -------------------------------
def extract_text_from_pdf(pdf):
    doc = fitz.open(stream=pdf.read(), filetype="pdf")
    full_text = ""
    for page in doc:
        full_text += page.get_text()
    return full_text

def normalize_text(text):
    text = re.sub(r'\s+', ' ', text)  # remove extra spaces/newlines
    replacements = {
        "HEC-RAS": "H E C R A S",
        "SWMM": "S W M M",
        "β": "beta",
        "α": "alpha",
        "μ": "mu",
        "°C": "degrees Celsius",
        "m³/s": "cubic meters per second"
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text

def split_into_sentences(text):
    return sent_tokenize(text)

def summarize_section(text, max_sentences=50):
    """Optional: summarize long sections for faster TTS"""
    sentences = split_into_sentences(text)
    return " ".join(sentences[:max_sentences])

def text_to_speech_gTTS(text, filename="article.mp3"):
    tts = gTTS(text=text, lang="en")
    tts.save(filename)
    return filename

# -------------------------------
# 3️⃣ Process PDF and Generate Audio
# -------------------------------
if pdf_file is not None:
    st.info("Processing PDF... This may take a few seconds depending on the length.")

    # Extract text
    raw_text = extract_text_from_pdf(pdf_file)
    clean_text = normalize_text(raw_text)
    summary = summarize_section(clean_text, max_sentences=100)  # first 100 sentences

    # Generate TTS audio
    audio_file = text_to_speech_gTTS(summary, "article.mp3")

    st.success("✅ PDF processed successfully! Listen below:")

    # Play audio
    audio_bytes = open(audio_file, "rb").read()
    st.audio(audio_bytes, format="audio/mp3")

    # Optionally, provide a download button
    st.download_button(
        label="💾 Download MP3",
        data=audio_bytes,
        file_name="article.mp3",
        mime="audio/mp3"
    )

