# -*- coding: utf-8 -*-
"""app1.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18BGiVrfrCHc0H37myevUCd8JUpA9wgpg
"""

# app.py
import streamlit as st
import fitz  # PyMuPDF
import re
from gtts import gTTS
from nltk.tokenize import sent_tokenize
import nltk
import os

# Download nltk punkt tokenizer (only once)
nltk.download('punkt')

# -------------------------------
# Helper functions
# -------------------------------
def extract_text_from_pdf(pdf_file):
    doc = fitz.open(stream=pdf_file.read(), filetype="pdf")
    full_text = ""
    for page in doc:
        full_text += page.get_text()
    return full_text

def normalize_text(text):
    text = re.sub(r'\s+', ' ', text)  # Remove extra spaces/newlines
    replacements = {
        "HEC-RAS": "H E C R A S",
        "SWMM": "S W M M",
        "β": "beta",
        "α": "alpha",
        "μ": "mu",
        "°C": "degrees Celsius",
        "m³/s": "cubic meters per second"
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text

def split_into_sentences(text):
    return sent_tokenize(text)

def summarize_text(text, max_sentences=50):
    sentences = split_into_sentences(text)
    return " ".join(sentences[:max_sentences])

def text_to_speech_gTTS(text, filename="output.mp3"):
    tts = gTTS(text=text, lang="en")
    tts.save(filename)
    return filename

# -------------------------------
# Streamlit App UI
# -------------------------------
st.title("PDF to Speech Reader")
st.write("Upload a PDF file and listen to its content!")

pdf_file = st.file_uploader("Choose a PDF file", type=["pdf"])

if pdf_file:
    with st.spinner("Extracting text from PDF..."):
        raw_text = extract_text_from_pdf(pdf_file)

    clean_text = normalize_text(raw_text)
    summary = summarize_text(clean_text, max_sentences=50)  # adjust as needed

    st.subheader("Extracted Text (first 50 sentences)")
    st.write(summary)

    with st.spinner("Converting text to speech..."):
        audio_file = text_to_speech_gTTS(summary)

    st.audio(audio_file, format='audio/mp3')
    st.success("Done! You can listen above.")

